image: Visual Studio 2017

environment:
 matrix:
  - solution_path: Lazy\Lazy.sln
  - solution_path: MyNUnit\MyNUnit.sln
 
before_build:
  - nuget restore %solution_path%

build_script:
- msbuild %solution_path%
